"""Prhyme music player backend — browse + stream audio from on-device storage.

Offline-first: scans local directories only, no cloud calls.

Scanned sources:
  1. /storage/emulated/0/Music/      (phone music library)
  2. /storage/emulated/0/Download/   (downloaded tracks)
  3. <app>/outputs/                 (beats generated by Prhyme)

Endpoints (registered on the `player_bp` blueprint):
  GET /api/player/files            -> JSON list of audio files
  GET /api/player/stream/<file_id> -> audio bytes (supports HTTP Range for seeking)
"""
import hashlib
import mimetypes
import os
import re
import threading
import time

from flask import Blueprint, Response, jsonify, request

bp = Blueprint("player", __name__)

AUDIO_EXTS = {
    ".mp3", ".wav", ".m4a", ".aac", ".ogg", ".oga", ".opus",
    ".flac", ".wma", ".aiff", ".aif",
}

# Phone shared-storage roots. Guarded with isdir() so this module is also
# safe to import on the cloud deploy (they simply won't exist there).
_PHONE_ROOT = "/storage/emulated/0"

# Set by init_player() from app.py
_OUTPUTS_DIR = None

_scan_lock = threading.Lock()
_scan_cache = {"at": 0.0, "files": [], "by_id": {}}
SCAN_TTL = 30.0  # seconds
SCAN_CAP = 10000  # max tracks indexed (Daryl: shuffle up to 10k without repeats)


def init_player(outputs_dir):
    global _OUTPUTS_DIR
    _OUTPUTS_DIR = outputs_dir


def _source_dirs():
    dirs = []
    for label, sub in (("Music", "Music"), ("Downloads", "Download")):
        p = os.path.join(_PHONE_ROOT, sub)
        if os.path.isdir(p):
            dirs.append((label, p))
    if _OUTPUTS_DIR and os.path.isdir(_OUTPUTS_DIR):
        dirs.append(("Generated", _OUTPUTS_DIR))
    return dirs


def _file_id(path):
    real = os.path.realpath(path)
    return hashlib.sha1(real.encode("utf-8")).hexdigest()[:16]


def _scan():
    """Walk source dirs, return (tracks, by_id registry). Respects SCAN_CAP."""
    tracks = []
    by_id = {}
    for label, root in _source_dirs():
        for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
            # Skip hidden dirs, keep walk shallow-ish for speed
            dirnames[:] = [d for d in dirnames
                           if not d.startswith(".") and d != "__pycache__"]
            depth = os.path.relpath(dirpath, root).count(os.sep)
            if depth > 5:
                dirnames[:] = []
                continue
            for fn in filenames:
                if len(tracks) >= SCAN_CAP:
                    break
                ext = os.path.splitext(fn)[1].lower()
                if ext not in AUDIO_EXTS or fn.startswith("."):
                    continue
                full = os.path.join(dirpath, fn)
                try:
                    st = os.stat(full)
                except OSError:
                    continue
                if st.st_size <= 0:
                    continue
                tid = _file_id(full)
                tracks.append({
                    "id": tid,
                    "name": os.path.splitext(fn)[0],
                    "filename": fn,
                    "source": label,
                    "size": st.st_size,
                    "mtime": int(st.st_mtime),
                    "ext": ext.lstrip("."),
                })
                by_id.setdefault(tid, os.path.realpath(full))
            if len(tracks) >= SCAN_CAP:
                break
        if len(tracks) >= SCAN_CAP:
            break
    # Newest first within each source, sources in Music/Downloads/Generated order
    order = {"Music": 0, "Downloads": 1, "Generated": 2}
    tracks.sort(key=lambda t: (order.get(t["source"], 9), -t["mtime"]))
    return tracks, by_id


def get_tracks(force=False):
    now = time.time()
    with _scan_lock:
        if force or now - _scan_cache["at"] > SCAN_TTL:
            files, by_id = _scan()
            _scan_cache["files"] = files
            _scan_cache["by_id"] = by_id
            _scan_cache["at"] = now
        return list(_scan_cache["files"])


def get_path(file_id):
    """Resolve a file_id to an absolute path, validated against source roots."""
    if not re.fullmatch(r"[0-9a-f]{16}", file_id or ""):
        return None
    get_tracks()  # make sure the registry is warm
    with _scan_lock:
        path = _scan_cache["by_id"].get(file_id)
    if not path or not os.path.isfile(path):
        return None
    real = os.path.realpath(path)
    roots = [r for _, r in _source_dirs()]
    if any(real == r or real.startswith(r + os.sep) for r in roots):
        return real
    return None


def _stream_file(path):
    size = os.path.getsize(path)
    mime = mimetypes.guess_type(path)[0] or "application/octet-stream"
    if mime.startswith("audio/x-"):
        mime = {"audio/x-m4a": "audio/mp4",
                "audio/x-wav": "audio/wav"}.get(mime, mime)
    start, end = 0, size - 1
    status = 200
    rh = request.headers.get("Range")
    if rh:
        m = re.match(r"bytes=(\d*)-(\d*)\s*$", rh)
        if m:
            if m.group(1):
                start = int(m.group(1))
            if m.group(2):
                end = int(m.group(2))
            if start >= size:
                return Response(status=416,
                                headers={"Content-Range": f"bytes */{size}"})
            end = min(end, size - 1)
            start = max(0, start)
            status = 206
    length = end - start + 1

    def gen():
        with open(path, "rb") as f:
            f.seek(start)
            remaining = length
            while remaining > 0:
                chunk = f.read(min(65536, remaining))
                if not chunk:
                    break
                remaining -= len(chunk)
                yield chunk

    headers = {
        "Accept-Ranges": "bytes",
        "Content-Length": str(length),
        "Cache-Control": "no-cache",
    }
    if status == 206:
        headers["Content-Range"] = f"bytes {start}-{end}/{size}"
    return Response(gen(), status=status, mimetype=mime,
                    headers=headers, direct_passthrough=True)


@bp.get("/api/player/files")
def api_player_files():
    force = request.args.get("refresh") == "1"
    tracks = get_tracks(force=force)
    return jsonify({
        "ok": True,
        "count": len(tracks),
        "sources": [label for label, _ in _source_dirs()],
        "files": tracks,
    })


@bp.get("/api/player/stream/<file_id>")
def api_player_stream(file_id):
    path = get_path(file_id)
    if not path or not os.path.isfile(path):
        return jsonify({"ok": False, "error": "Track not found"}), 404
    try:
        return _stream_file(path)
    except OSError:
        return jsonify({"ok": False, "error": "Could not read track"}), 500
